### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by do-n-khanh** [jthegedus/firebase-functions-es6-example#2]
I got this error when installing on MacOS

yarn install v0.24.6
error Error parsing JSON at "/Users/apple/Developer/ffes6/package.json", "/Users/apple/Developer/ffes6/package.json: Unexpected end of JSON input".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

How can I fix that?

**Comment by jthegedus** [comment]
Sorry about those errors, I forgot to merge my changes from the Gists (used in the Medium post) back into this repo. They should be fixed now!
